# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

variables:
  GH_TOKEN: farmerconnect:$(githubToken)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Npm@1
    displayName: Run npm install
    enabled: true
    continueOnError: false
    inputs:
      command: 'install'

  - task: Npm@1
    displayName: Run npm audit
    enabled: true
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'audit'

  - task: Npm@1
    displayName: Run npm run lint
    enabled: true
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'run lint'

  - task: Npm@1
    displayName: Run npm run build
    enabled: true
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'run build'

  - task: Npm@1
    displayName: Run npm run test
    enabled: true
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'run test'

  - task: Npm@1
    displayName: Publish to Azure Artifacts
    enabled: true
    continueOnError: false
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: 'publish'
      publishRegistry: 'useFeed'
      publishFeed: '099e7de5-5a11-4c12-a542-e808a6f5e8b3'

  - task: CmdLine@2
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      script: 'git remote set-url origin https://${{ variables.GH_TOKEN }}@github.com/farmerconnect/farmerconnect-ui.git'

  - task: Npm@1
    displayName: Build storybook
    enabled: true
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    continueOnError: true
    inputs:
      command: 'custom'
      customCommand: 'run build-storybook'

  - task: Npm@1
    displayName: Deploy to github pages
    enabled: true
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'run deploy-storybook -- --ci --existing-output-dir=storybook-static'
