# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

variables:
  GH_TOKEN: farmerconnect:$(githubToken)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: CmdLine@2
    displayName: install
    enabled: true
    continueOnError: false
    inputs:
      script: 'yarn install'

  - task: CmdLine@2
    displayName: audit
    enabled: true
    continueOnError: false
    inputs:
      script: 'yarn audit --groups dependencies'

  - task: CmdLine@2
    displayName: lint
    enabled: true
    continueOnError: false
    inputs:
      script: 'yarn lint'

  - task: CmdLine@2
    displayName: build
    enabled: true
    continueOnError: false
    inputs:
      script: 'yarn build'

  - task: CmdLine@2
    displayName: test
    enabled: true
    continueOnError: false
    inputs:
      script: 'yarn test'

  - task: Npm@1
    displayName: Publish to NPM
    enabled: true
    continueOnError: false
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: 'publish'
      publishEndpoint: 'NPMRegistry'

  - task: CmdLine@2
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      script: 'git remote set-url origin https://${{ variables.GH_TOKEN }}@github.com/farmerconnect/farmerconnect-ui.git'

  - task: Npm@1
    displayName: Build storybook
    enabled: true
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    continueOnError: true
    inputs:
      command: 'custom'
      customCommand: 'run build-storybook'

  - task: Npm@1
    displayName: Deploy to github pages
    enabled: true
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'run deploy-storybook -- --ci --existing-output-dir=storybook-static'

  - task: SnykSecurityScan@1
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      serviceConnectionEndpoint: 'snyk-service-connection'
      testType: 'app'
      severityThreshold: 'high'
      monitorWhen: 'never'
      failOnIssues: true
      additionalArguments: '--fail-on=all'

