name: Test, Build & Deployment
on:
  push:
    branches:
    - main

jobs:
  image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Current Image tag generated
        run: echo ${{ github.sha }}

  tests:
    uses: farmerconnect/pipeline-actions/.github/workflows/yarn-lint-build-test.yaml@main

  snyk-scan:
    uses: farmerconnect/pipeline-actions/.github/workflows/snyk-node.yaml@main
    secrets:
      snykToken: ${{ secrets.SNYK_TOKEN }}

  build:
    needs: [snyk-scan, tests]
    steps:
    - uses: actions/checkout@v2

    - name: Publish to NPM
      run: npm publish

    - name: Build storybook
      run: npm run build-storybook
      continue-on-error: true

    - name: Deploy to github pages
      run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}